### ISSUE TITLE
quotes removed from destination yml file

### ISSUE THREAD

**Issue by davidcsi** [termim/ruamel_yaml#1]
Hello,

First of all, thanks for this code, it's great!

I'm having a issue with quoted strings, though.
I have a file that contains something like:

```
  NETWORK_NODES: 10.10.0.1
  NETWORK_CONNECTIVITY_NODES: "172.18.0.20 172.18.0.21 172.18.0.24 172.18.0.25 172.18.0.2 172.18.0.7"
  AWS_ID: "blahblah"
  AWS_KEY: "more_blah"

```
and when i change NETWORK_NODES, the module removes the quotes and inserts a carriage return in "NETWORK_CONNECTIVITY_NODES":

```
  NETWORK_NODES: 10.10.0.1
  NETWORK_CONNECTIVITY_NODES: 172.18.0.20 172.18.0.21 172.18.0.24 172.18.0.25 172.18.0.2
    172.18.0.7
  AWS_ID: blahblah
  AWS_KEY: more_blah
```

Anyway to work around this?
Many thanks!

**Comment by davidcsi** [comment]
Also,

I'm replacing an IP in:
```
NETWORK_NODE: 1.2.3.4
```
to something new and i want to add a comment like this:
```
NETWORK_NODE: 10.10.10.1  #node-dns-name
```
Is this possible?

Thanks again!

**Comment by termim** [comment]
Please submit your questions to the package maintainer at https://sourceforge.net/projects/ruamel-yaml/
